services:
  - type: web
    name: airbnb-price-predictor
    env: python
    region: ohio
    branch: main
    rootDir: app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
